[package]
name = "remote-ff"
version = "3.0.0"
authors = ["Julian Blake Kongslie <jblake@jblake.org>"]

[dependencies]
clap = "*"
filetime = "*"
hyper = "*"
lazy_static = "*"
marksman_escape = "*"
rand = "*"
regex = "*"
rusqlite = "*"
rustc-serialize = "*"
rustful = "*"
scraper = "*"
time = "*"
