#!/bin/bash

set -eux

cd ~/remote-ff

rm -rf old-books
cp -rl books old-books

time timeout 1h ./fetch.rb

cd books
ls -lt --time-style=+%Y-%m-%d | awk -e '{print $6, $7}' > /srv/www/jblake/books.txt
