#!/bin/bash

set -eux

cd ~/remote-ff

fusermount -u peer > /dev/null 2>&1 || true

cargo build --release

mkdir -p peer

until sshfs -C -o entry_timeout=600 -o attr_timeout=600 tablet:/ peer; do
  sleep 0.1
done

ls -lR peer/storage/emulated/0/Books > /dev/null &
ssh tablet "while pkill com.flyersoft.moonreaderp; do sleep 1; done" &

wait

time target/release/remote-ff sync peer || true

fusermount -u peer > /dev/null 2>&1 || true
