#!/bin/bash

set -eux

cd ~/remote-ff

ssh tablet-fwd "while pkill com.flyersoft.moonreaderp; do sleep 1; done"

./mkupdate.rb db.json > books/update.sql

rsync --archive --progress books/ tablet-fwd:/storage/emulated/0/Books/

ssh tablet-fwd "sqlite3 -batch /data/data/com.flyersoft.moonreaderp/databases/mrbooks.db < /storage/emulated/0/Books/update.sql"

cd books
touch LAST-SYNC
ls -lt --time-style=+%Y-%m-%d | awk -e '{print $6, $7}' > /srv/www/jblake/books.txt
